<?php

$config=array();
$config['title']='osWFrame:Core';
$config['elements']=array();
$config['elements'][]=array(
	'title'=>'PHP:Version',
	'value'=>'5.3.0',
	'required'=>true,
	'getvalue'=>PHP_MAJOR_VERSION.'.'.PHP_MINOR_VERSION.'.'.PHP_RELEASE_VERSION,
	'check'=>'version_compare',
	'check_operator'=>'>=',
);
$config['elements'][]=array(
	'title'=>'PHP:Bit',
	'value'=>64,
	'required'=>false,
	'getvalue'=>(intval(-6981276091)==-6981276091)?64:32,
	'check'=>'int',
	'check_operator'=>'=',
);
$config['elements'][]=array(
	'title'=>'Config:short_open_tag',
	'value'=>0,
	'required'=>false,
	'getvalue'=>intval(ini_get('short_open_tag')),
	'check'=>'boolint',
	'check_operator'=>'=',
);

?>